// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSgqtfIgIkne0SzjfIBzz7axrk2PPElQ',
    appId: '1:269030990123:web:41c2ce3d3d90ebbb22e56e',
    messagingSenderId: '269030990123',
    projectId: 'feffs-8fd86',
    authDomain: 'feffs-8fd86.firebaseapp.com',
    storageBucket: 'feffs-8fd86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvTLBGTFc3RTkSwcGkkULwsz8W2JIls0',
    appId: '1:269030990123:android:154f2ee3fac6871c22e56e',
    messagingSenderId: '269030990123',
    projectId: 'feffs-8fd86',
    storageBucket: 'feffs-8fd86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9EWK6MgAxp4w7XIh0uTLLZQc-thEhQ0',
    appId: '1:269030990123:ios:65e16e6e484d011622e56e',
    messagingSenderId: '269030990123',
    projectId: 'feffs-8fd86',
    storageBucket: 'feffs-8fd86.firebasestorage.app',
    iosBundleId: 'com.example.feffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9EWK6MgAxp4w7XIh0uTLLZQc-thEhQ0',
    appId: '1:269030990123:ios:65e16e6e484d011622e56e',
    messagingSenderId: '269030990123',
    projectId: 'feffs-8fd86',
    storageBucket: 'feffs-8fd86.firebasestorage.app',
    iosBundleId: 'com.example.feffs',
  );
}
